//----------------------
// <auto-generated>
//     GENERATED BY ZEBBLE
// </auto-generated>
#pragma warning disable  IDE0017, CS0108, CS0436
//----------------------

#region UI.Templates.Blank
namespace UI.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Templates\Blank.zbl")]
    partial class Blank : Page
    {
        public ScrollView Body = new ScrollView();
        public Stack Wrapper = new Stack();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Body.Id = "Body";
            Body.CssClass = "Body";

            Wrapper.Id = "Wrapper";
            Wrapper.CssClass = "Wrapper";

            await Body.Add(Wrapper);
            await Add(Body);
        }
    }
}
#endregion

#region UI.Pages.Home
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Home.zbl")]
    partial class Home : Page
    {
        public Stack holder = new Stack();
        public TextView main = new TextView();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            holder.Id = "holder";

            main.Id = "main";
            main.Text = "Hello World from zebble!";

            await holder.Add(main);
            await Add(holder);
        }
    }
}
#endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "C8VDOg2sBTQC6T6UwZZ8RiBf1I";
    }
}
