//----------------------
// <auto-generated>
//     GENERATED BY ZEBBLE
// </auto-generated>
#pragma warning disable  IDE0017, CS0108, CS0436
//----------------------

#region UI.Pages.CategoriesPage
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\CategoriesPage.zbl")]
    partial class CategoriesPage : Page
    {
        public Stack Scaffold = new Stack();
        public ListView<Domain.Models.Category, UI.Modules.CategoryListItem> CategoriesList = new ListView<Domain.Models.Category, UI.Modules.CategoryListItem>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Scaffold.Id = "Scaffold";

            CategoriesList.Id = "CategoriesList";

            var __stack1 = new Stack() { CssClass = "PrimaryButton" }.On(x => x.Tapped, ChangeTheme);

            var __textView1 = new TextView() { Text = "Change Theme" };

            await __stack1.Add(__textView1);
            await Scaffold.AddRange(new View[] { CategoriesList, __stack1 });
            await Add(Scaffold);
        }
    }
}
#endregion

#region UI.Pages.SubjectPage
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\SubjectPage.zbl")]
    partial class SubjectPage : Page
    {
        public Stack Scaffold = new Stack();
        public ScrollView ScrollHolder = new ScrollView();
        public CollectionView<WordInfoVM, ItemTemp> SubjectList = new CollectionView<WordInfoVM, ItemTemp>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            Scaffold.Id = "Scaffold";

            var __stack1 = new Stack() { CssClass = "PrimaryButton" }.On(x => x.Tapped, GoBack);

            var __textView1 = new TextView() { Text = "Back" };

            ScrollHolder.Id = "ScrollHolder";

            SubjectList.Id = "SubjectList";
            SubjectList.ShouldMeasureForAll = false;

            await __stack1.Add(__textView1);
            await ScrollHolder.Add(SubjectList);
            await Scaffold.AddRange(new View[] { __stack1, ScrollHolder });
            await Add(Scaffold);
        }

        [CacheView]
        [EscapeGCop("Auto-generated")]
        [SourceCode(@"Views\Pages\SubjectPage.zbl")]
        public partial class ItemTemp : Modules.SubjectListItem, ITemplate<WordInfoVM>
        {
            public WordInfoVM Model = Zebble.Mvvm.ViewModel.The<WordInfoVM>();

            protected override async Task InitializeFromMarkup()
            {
                await base.InitializeFromMarkup();

                this.CssClass = "ListItem";
                this.ClipChildren = true;
                this.AutoFlash = false;

                this.Bind("WordInfo", () => Model.Source,x=>x);
            }
            }}
        }
        #endregion

#region UI.Modules.CategoryListItem
namespace UI.Modules
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Modules\CategoryListItem.zbl")]
    partial class CategoryListItem : ListViewItem<Domain.Models.Category>
    {
        public TextView CategoryName = new TextView();
        public RecyclerCarousel<Domain.Models.Subject, UI.Modules.SlideTemplate> Carousel = new RecyclerCarousel<Domain.Models.Subject, UI.Modules.SlideTemplate>();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            var __stack1 = new Stack();

            CategoryName.Id = "CategoryName";
            CategoryName.Bind("Text", () => CategoryItem, x=>x.Name);

            Carousel.Id = "Carousel";
            Carousel.ShowBullets = false;
            Carousel.CenterAligned = false;
            Carousel.SlideWidth = 80;
            Carousel.ClipChildren = false;

            await __stack1.AddRange(new View[] { CategoryName, Carousel });
            await Add(__stack1);
        }
    }
}
#endregion

#region UI.Modules.SlideTemplate
namespace UI.Modules
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Modules\SlideTemplate.zbl")]
    partial class SlideTemplate : RecyclerCarouselSlide<Domain.Models.Subject>
    {
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            this.ClipChildren = false;

            var __stack1 = new Stack() { CssClass = "CategorySlide" }.On(x => x.Tapped, OnSlideTapped);

            var __imageView1 = new ImageView() { CssClass = "SubjectImage", Stretch = Stretch.AspectFill }.Bind("Path", () => Item, x=>x.ImageURL);

            var __textView1 = new TextView() { CssClass = "SubjectName", Wrap = true }.Bind("Text", () => Item, x=>x.Name);

            await __stack1.AddRange(new View[] { __imageView1, __textView1 });
            await Add(__stack1);
        }
    }
}
#endregion

#region UI.Modules.SubjectListItem
namespace UI.Modules
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Modules\SubjectListItem.zbl")]
    partial class SubjectListItem : Stack
    {
        public Stack TextHolder = new Stack();
        public TextView WordTitle = new TextView();
        public TextView WordRank = new TextView();
        public TextView WordSub = new TextView();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            TextHolder.Id = "TextHolder";

            WordTitle.Id = "WordTitle";

            WordRank.Id = "WordRank";

            WordSub.Id = "WordSub";

            await TextHolder.AddRange(new View[] { WordTitle, WordRank, WordSub });
            await Add(TextHolder);
        }
    }
}
#endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "yW4PZ8WCZRNtI3LpbAJth5Vo5g";
    }
}
