//----------------------
// <auto-generated>
//     GENERATED BY ZEBBLE
// </auto-generated>
#pragma warning disable  IDE0017, CS0108, CS0436
//----------------------

#region UI.Pages.Home
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;
    using Olive;
    using Zebble.Services.Css;

    [EscapeGCop("Auto-generated")]
    [SourceCode(@"Views\Pages\Home.zbl")]
    partial class Home : Page
    {
        public Stack holder = new Stack();
        public ImageView Img = new ImageView();
        public Stack TextBox = new Stack();
        public TextView Title = new TextView();
        public TextView Message = new TextView();
        public Stack NormalButton = new Stack();
        public TextView ButtonTextView = new TextView();
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            holder.Id = "holder";

            Img.Id = "Img";
            Img.Path = "Images/GreatJob.png";

            TextBox.Id = "TextBox";

            Title.Id = "Title";
            Title.Text = "Great Job!";

            Message.Id = "Message";
            Message.Text = "Keep up the good work";

            NormalButton.Id = "NormalButton";
            NormalButton.On(x => x.Tapped, ChangeThemeBtnTapped);

            ButtonTextView.Id = "ButtonTextView";
            ButtonTextView.Text = "Change theme";

            await TextBox.AddRange(new View[] { Title, Message });
            await NormalButton.Add(ButtonTextView);
            await holder.AddRange(new View[] { Img, TextBox, NormalButton });
            await Add(holder);
        }
    }
}
#endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "m3c7rKTPWW6HtrsI7fRJvFPDS6U";
    }
}
